[tool.poetry]
name = "photo-utils"
version = "0.1.0"
description = ""
authors = ["Duncan Grubbs <duncan.grubbs@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
exif = "^1.6.0"
tqdm = "^4.66.5"
typer = "^0.12.5"
structlog = "^24.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
